version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Synel.Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5000:80
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: X@CiWc&Ve%MO